# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-07 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vemax', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='list_friend',
            field=models.CharField(default=b'', max_length=5000),
        ),
    ]
